/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_bluerose73_fiji_dcimg_DcimgReader */

#ifndef _Included_io_bluerose73_fiji_dcimg_DcimgReader
#define _Included_io_bluerose73_fiji_dcimg_DcimgReader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_bluerose73_fiji_dcimg_DcimgReader
 * Method:    ReadSize
 * Signature: (Ljava/lang/String;)Lio/bluerose73/fiji/dcimg/DcimgReader/Size;
 */
JNIEXPORT jobject JNICALL Java_io_bluerose73_fiji_dcimg_DcimgReader_ReadSize
  (JNIEnv *, jclass, jstring);

/*
 * Class:     io_bluerose73_fiji_dcimg_DcimgReader
 * Method:    ReadFrame
 * Signature: (Ljava/lang/String;I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_io_bluerose73_fiji_dcimg_DcimgReader_ReadFrame
  (JNIEnv *, jclass, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
